nitrous = true				# enables nitrous, bound to the ALT key or B on controller
rev_limiter = true			# enables the rev limiter, set to false to have higher RPMs
upgrade_level = 1.0			# set to 0.0 for have stock cars, 1.0 for fully tuned Junkman parts