[CUSTOM]
OVERSTEER_TC_MULT=500

[GEARS]
UP=4900
DOWN=4500

[LOOKAHEAD]
BASE=25.2
GAS_BRAKE_LOOKAHEAD=0

[PEDALS]
BRAKE_HINT=3

[PHYSICS_HINTS]
AERO_HINT=1

[STEER]
STEER_GAIN=0.3

[TYRES]
HINT=1.7

[ULTRA_GRIP]
VALUE=1

[UNDERSTEER]
HINT=1